### ISSUE TITLE
bug in vim v7.4.2146

### ISSUE THREAD

**Issue by QiWei** [othree/vim-autocomplpop#11] opened 2016-08-08 17:58 UTC
in vim v7.4.2146 auto insert unpredictable char (from next line)

**Comment by othree** [comment] 2016-08-09 02:56
Hi when did you notice this issue?
Are you just update Vim to latest reversion.
If yes what is your previous version?

**Comment by akanosora** [comment] 2016-08-10 04:48
I have the same issue. It is caused by line 251 and line 259 in vim-autocomplpop/autoload/acp.vim. The <C-e> copies the character under the cursor (from the next line) if <C-n> fails to popup menu. This was not an issue in previous version... not sure why...

VIM help about <C-e> under Insert mode:
http://vimdoc.sourceforge.net/htmldoc/scroll.html#CTRL-E

**Comment by akanosora** [comment] 2016-08-10 05:21
Okay I reported this to MacVim community and it indeed is due to change of VIM behavior by default. Please see: https://groups.google.com/forum/#!msg/vim_dev/e2Rr8Px3qkQ/1XWiAQ0LAgAJ

**Comment by skilbjo** [comment] 2016-08-10 07:54
I drove myself insane trying to figure out what was wrong with my keybindings! Sure learned a hell of a lot more about vim than I do 2 days ago :)

+1 on the issue

A quick workaround for others experiencing the issue (I'm on mac / homebrew) is to just revert back to the older version of vim:

```$ ls /usr/local/Cellar/vim
> 7.4.2109    7.4.2152
$ brew switch 7.4.2109```

**Comment by skilbjo** [comment] 2016-08-10 08:02
Should be fixed in the next version of vim: https://github.com/vim/vim/issues/972

**Comment by akanosora** [comment] 2016-08-10 14:03
Yeah, seems patch 2146 is the culprit. I am glad that they reverted it back.

**Closed** 2016-10-07 06:55 UTC
